:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:toc: macro

= Mobile Development with Ionic, React Native, Flutter, and JHipster

The brackets at the end of each step indicate the alias's or IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

**Prerequisites:**

* https://adoptopenjdk.net/[Java 11+]
* https://nodejs.org[Node 14+]

toc::[]

NOTE: I've purposely left the version numbers off this tutorial's `npm install` commands so the latest versions will be used. If you find issues with these steps, please file an issue for this repo.

== Build a Photo Gallery with JHipster (React + Spring Boot)

. Create a new directory to hold all the projects: `take mobile-jhipster`

. Clone an existing JHipster app into a `backend` directory:

  git clone https://github.com/oktadev/auth0-full-stack-java-example.git backend
  rm -rf backend/.git

. Modify `backend/package.json` to remove the `prepare` script that installs Husky.

  "prepare": "husky install",

. Start Keycloak:

  cd backend
  docker-compose -f src/main/docker/keycloak.yml up -d

. Start app using `./mvnw`, show project in IDE, and browse `http://localhost:8080`

. Add a few photos and show lightbox

== Create an Ionic App

. Install Ionic CLI and Ionic for JHipster

  npm i -g generator-jhipster-ionic @ionic/cli yo

. Create an Ionic app named `Flickr2`

  yo jhipster-ionic

. Rename `Flickr2` to `ionic`

  mv Flickr2 ionic
  cd ionic

. Launch app and log in after running `ionic serve`

. Generate entities

  yo jhipster-ionic:import-jdl ../backend/flickr2.jdl

. Show generated entity screens and photos

. Hide metadata in `photo-update.html` with `<div *ngIf="!isNew">`

. Add your custom scheme to `ios/App/App/Info.plist`:
+
[source,xml]
----
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLName</key>
    <string>com.getcapacitor.capacitor</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>capacitor</string>
      <string>dev.localhost.ionic</string>
    </array>
  </dict>
</array>
----

. Modify the JHipster app's CORS settings (in `backend/src/main/resources/config/application-dev.yml`) to allow `capacitor://localhost` as an origin.

. Run your app in Simulator.

  npx cap run ios

. You can also open your project in Xcode and run it from there.

  npx cap open ios

// npm run e2e

////
Change the custom scheme in `android/app/src/main/res/values/strings.xml` to use `dev.localhost.ionic`:

```xml
<string name="custom_url_scheme">dev.localhost.ionic</string>
```

```
npm install jetifier
npx jetify
npx cap sync android
```

Then, run your project using the Capacitor CLI:

```
npx cap run android
```

You'll need to run a couple commands to allow the emulator to communicate with JHipster and Keycloak.

```
adb reverse tcp:8080 tcp:8080
adb reverse tcp:9080 tcp:9080
```

If you see `java.io.IOException: Cleartext HTTP traffic to localhost not permitted` in your Android Studio console, enable clear text traffic in `android/app/src/main/AndroidManifest.xml`:

```xml
<application
    ...
    android:usesCleartextTraffic="true">

////

== Generate a React Native App

. Install React Native JHipster and Expo CLI

  npm install -g generator-jhipster-react-native expo-cli

. Create a React Native client:

  take react-native
  jhipster --blueprints react-native jdl ../app.jdl

. Name your app `Flickr2` when prompted

. Change `application-dev.yml` in backend to allow `\http://localhost:19006` for CORS

. Add `\https://auth.expo.io/@mraible/Flickr2` as a Login redirect URI in Keycloak

. Hide metadata in add photo screen when `isNewEntity`
+
[source,jsx]
----
  const metadata = (
    <div>...</div>
  )
  const metadataRows = isNewEntity ? '' : metadata;
----

. To run on emulators, you'll need an https://expo.io/[Expo] account

. In the `react-native` directory, run `npm start`

. For Android emulators to communicate with your API and Keycloak, add some port mappings

  adb reverse tcp:8080 tcp:8080 && adb reverse tcp:9080 tcp:9080

. Refresh your app in Simulator using kbd:[{commandkey} + R] or by hitting kbd:[R] twice in Android

== Develop a Flutter App

. Install Flutter for JHipster

  npm install -g generator-jhipster-flutter-merlin
+
NOTE: This module currently only supports JWT auth. There's open issues for https://github.com/merlinofcha0s/generator-jhipster-flutter/issues/23[Keycloak] and https://github.com/merlinofcha0s/generator-jhipster-flutter/issues/31[Okta] support.

. Install Flutter SDK and upgrade

  brew install --cask flutter
  flutter upgrade
  # accept Android licenses
  flutter doctor --android-licenses
  # Needs Java 8 because NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
  sdk use java 8.0.242.hs-adpt

. Create a Flutter app in the `backend` directory

  yo jhipster-flutter-merlin # creates flutter-app directory

. Run your app

  cd flutter-app
  flutter run

NOTE: See https://github.com/merlinofcha0s/generator-jhipster-flutter/issues/50[generator-jhipster-flutter/issues/50] for issues I had with JHipster 7.

== Use Auth0 for Identity

. Log in to your Auth0 account (or https://auth0.com/signup[sign up] if you don't have an account). You should have a unique domain like `dev-xxx.us.auth0.com`.

. Press the *Create Application* button in https://manage.auth0.com/#/applications[Applications section]. Use a name like `JHipster Baby!`, select `Regular Web Applications`, and click *Create*.

. Switch to the *Settings* tab and configure your application settings:
+
- Allowed Callback URLs: `\http://localhost:8080/login/oauth2/code/oidc`
- Allowed Logout URLs: `\http://localhost:8080/`

. Scroll to the bottom and click *Save Changes*.

. In the https://manage.auth0.com/#/roles[roles] section, create new roles named `ROLE_ADMIN` and `ROLE_USER`.

. Create a new user account in the https://manage.auth0.com/#/users[users] section. Click on the *Role* tab to assign the roles you just created to the new account.
+
_Make sure your new user's email is verified before attempting to log in!_

. Next, head to *Auth Pipeline* > *Rules* > *Create*. Select the `Empty rule` template. Provide a meaningful name like `Group claims` and replace the Script content with the following.
+
[source,js]
----
function(user, context, callback) {
  user.preferred_username = user.email;
  const roles = (context.authorization || {}).roles;

  function prepareCustomClaimKey(claim) {
    return `https://www.jhipster.tech/${claim}`;
  }

  const rolesClaim = prepareCustomClaimKey('roles');

  if (context.idToken) {
    context.idToken[rolesClaim] = roles;
  }

  if (context.accessToken) {
    context.accessToken[rolesClaim] = roles;
  }

  callback(null, user, context);
}
----
+
This code is adding the user's roles to a custom claim (prefixed with `https://www.jhipster.tech/roles`). This claim is mapped to Spring Security authorities in `SecurityUtils.java`.

. Click *Save changes* to continue.

. Create a `backend/.auth0.env` file and populate it with your Auth0 settings.
+
[source,shell]
----
export SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://<your-auth0-domain>/
export SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=<your-client-id>
export SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=<your-client-secret>
export JHIPSTER_SECURITY_OAUTH2_AUDIENCE=https://<your-auth0-domain>/api/v2/
----
+
You can use the default `Auth0 Management API` audience value from the *Applications* > *API* > *API Audience* field. You can also define your own custom API and use the identifier as the API audience.

=== Create a Native OIDC App

. For Ionic and React Native, create a *Native* app and add the following Allowed Callback URLs:

  http://localhost:19006/,https://auth.expo.io/@mraible/Flickr2,http://localhost:8100/callback,dev.localhost.ionic:/callback

. Copy the client ID to `react-native/app/config/app-config.js`.

. Set the Allowed Logout URLs to:

  http://localhost:8100/logout,dev.localhost.ionic:/logout

. Set the Allowed Origins (CORS) to `http://localhost:8100`.

. Update `ionic/src/app/auth/auth-config.service.ts` to use the generated client ID:

  environment.oidcConfig.server_host = this.authConfig.issuer;
  environment.oidcConfig.client_id = 'Dz7Oc9Zv9onjUBsdC55wReC4ifGMlA7G';

. Change logic to set email from `preferred_username` in `UserService` since Auth0 doesn't send email claim.

. Update `environment.ts` to specify your audience.
+
[source,ts]
----
export const environment = {
  ...
  oidcConfig: {
    ...
    audience: 'https://<your-auth0-domain>/api/v2/'
  },
  ...
};
----

. Modify Ionic's `login.page.ts` and `welcome.page.ts` to pass in `audience` as a parameter.

  await this.authService.signIn({ audience: environment.oidcConfig.audience });

. Restart your mobile apps and log in with Auth0!
+
----
# Ionic
npx cap run ios

# React Native
npm start
----

////

- Ionic with Auth0 needs audience in authorize request
- React Native with Auth0 needs audience
- Doesn't work:
    - React Native Android login
    - Ionic Android login
- Need to figure out /userinfo or given_name claims for Auth0

////

== Use Okta for Identity

. Install the https://cli.okta.com[Okta CLI] and run `okta register` to sign up for a new account. If you already have an account, run `okta login`.

. In the `backend` directory, run `okta apps create jhipster`. Select the default app name, or change it as you see fit. Accept the default Redirect URI values provided for you.

. The Okta CLI streamlines configuring a JHipster app and does several things for you:

1. Creates an OIDC app with the correct redirect URIs:
  - login: `\http://localhost:8080/login/oauth2/code/oidc` and `\http//localhost:8761/login/oauth2/code/oidc`
  - logout: `\http//localhost:8080` and `\http//localhost:8761`
2. Creates `ROLE_ADMIN` and `ROLE_USER` groups that JHipster expects
3. Adds your current user to the `ROLE_ADMIN` and `ROLE_USER` groups
4. Creates a `groups` claim in your default authorization server and adds the user's groups to it
+
NOTE: The `\http://localhost:8761*` redirect URIs are for the JHipster Registry, which is often used when creating microservices with JHipster. The Okta CLI adds these by default.

=== Create a Native OIDC App

. Create a *Native* app using `okta apps create` and use the following redirect URIs:

  http://localhost:19006/,https://auth.expo.io/@mraible/Flickr2,http://localhost:8100/callback,dev.localhost.ionic:/callback

. Set the Logout URIs to:

  http://localhost:8100/logout,dev.localhost.ionic:/logout

. Copy the client ID to `react-native/app/config/app-config.js`

. Update `ionic/src/app/auth/auth-config.service.ts` to use the new client ID

  environment.oidcConfig.server_host = '0oabzvz5mGpjjAT5o5d6';
  environment.oidcConfig.client_id = this.authConfig.clientId;

. Restart your mobile apps and log in with Okta!
+
----
# Ionic
npx cap run ios

# React Native
npm start
----

== Add Claims to Access Token

NOTE: These steps are only necessary if you are using JHipster v6, or JHipster v7 with a Reactive JHipster backend.

. Add `groups`, `given_name`, and `family_name` as claims to the access token.

* For `given_name`, use expression `user.firstName`
* For `family_name`, use expression `user.lastName`

Source: https://developer.okta.com/blog/2019/06/24/ionic-4-angular-spring-boot-jhipster[Build Mobile Apps with Angular, Ionic 4, and Spring Boot] and https://jruddell.com/blog/jhipster-react-native[JHipster React Native Demo].
